// Generated from the curated names in icons.ts: an explicit map keeps the bundle to just these icons.
// Regenerate if icons.ts changes (every name must exist in @phosphor-icons/react as <PascalCase>Icon).
import type { Icon } from '@phosphor-icons/react'
import {
  AirplaneTiltIcon,
  AppleLogoIcon,
  BarbellIcon,
  BasketIcon,
  BathtubIcon,
  BedIcon,
  BeerSteinIcon,
  BicycleIcon,
  BoatIcon,
  BookBookmarkIcon,
  BookOpenIcon,
  BooksIcon,
  BrainIcon,
  BroomIcon,
  BusIcon,
  CakeIcon,
  CalculatorIcon,
  CalendarBlankIcon,
  CameraIcon,
  CarIcon,
  CarrotIcon,
  ChalkboardTeacherIcon,
  ChampagneIcon,
  ChatsCircleIcon,
  CoffeeIcon,
  CompassIcon,
  ConfettiIcon,
  CookingPotIcon,
  CouchIcon,
  DogIcon,
  DropIcon,
  EnvelopeSimpleIcon,
  ExamIcon,
  FilmSlateIcon,
  FirstAidIcon,
  FlaskIcon,
  FlowerLotusIcon,
  FlowerTulipIcon,
  ForkKnifeIcon,
  GameControllerIcon,
  GiftIcon,
  GlobeHemisphereWestIcon,
  GraduationCapIcon,
  GuitarIcon,
  HandWavingIcon,
  HeadphonesIcon,
  HeartIcon,
  HeartbeatIcon,
  HouseIcon,
  KeyIcon,
  LampIcon,
  LaptopIcon,
  LightbulbIcon,
  ListChecksIcon,
  MapPinIcon,
  MicrophoneStageIcon,
  MicroscopeIcon,
  MoonIcon,
  MountainsIcon,
  MusicNotesIcon,
  NotebookIcon,
  PaintBrushIcon,
  PaletteIcon,
  PenNibIcon,
  PencilLineIcon,
  PersonSimpleBikeIcon,
  PersonSimpleRunIcon,
  PhoneIcon,
  PianoKeysIcon,
  PillIcon,
  PlantIcon,
  PresentationChartIcon,
  PuzzlePieceIcon,
  ScissorsIcon,
  ShoppingCartIcon,
  ShowerIcon,
  SmileyIcon,
  SneakerMoveIcon,
  StarIcon,
  StudentIcon,
  SuitcaseIcon,
  SunIcon,
  SwimmingPoolIcon,
  TShirtIcon,
  TaxiIcon,
  TelevisionSimpleIcon,
  TentIcon,
  TicketIcon,
  ToothIcon,
  TrainIcon,
  TranslateIcon,
  TrashIcon,
  UmbrellaIcon,
  UsersThreeIcon,
  VanIcon,
  VideoCameraIcon,
  WashingMachineIcon,
  WineIcon,
  WrenchIcon,
} from '@phosphor-icons/react'

export const ICON_COMPONENTS: Record<string, Icon> = {
  'airplane-tilt': AirplaneTiltIcon,
  'apple-logo': AppleLogoIcon,
  'barbell': BarbellIcon,
  'basket': BasketIcon,
  'bathtub': BathtubIcon,
  'bed': BedIcon,
  'beer-stein': BeerSteinIcon,
  'bicycle': BicycleIcon,
  'boat': BoatIcon,
  'book-bookmark': BookBookmarkIcon,
  'book-open': BookOpenIcon,
  'books': BooksIcon,
  'brain': BrainIcon,
  'broom': BroomIcon,
  'bus': BusIcon,
  'cake': CakeIcon,
  'calculator': CalculatorIcon,
  'calendar-blank': CalendarBlankIcon,
  'camera': CameraIcon,
  'car': CarIcon,
  'carrot': CarrotIcon,
  'chalkboard-teacher': ChalkboardTeacherIcon,
  'champagne': ChampagneIcon,
  'chats-circle': ChatsCircleIcon,
  'coffee': CoffeeIcon,
  'compass': CompassIcon,
  'confetti': ConfettiIcon,
  'cooking-pot': CookingPotIcon,
  'couch': CouchIcon,
  'dog': DogIcon,
  'drop': DropIcon,
  'envelope-simple': EnvelopeSimpleIcon,
  'exam': ExamIcon,
  'film-slate': FilmSlateIcon,
  'first-aid': FirstAidIcon,
  'flask': FlaskIcon,
  'flower-lotus': FlowerLotusIcon,
  'flower-tulip': FlowerTulipIcon,
  'fork-knife': ForkKnifeIcon,
  'game-controller': GameControllerIcon,
  'gift': GiftIcon,
  'globe-hemisphere-west': GlobeHemisphereWestIcon,
  'graduation-cap': GraduationCapIcon,
  'guitar': GuitarIcon,
  'hand-waving': HandWavingIcon,
  'headphones': HeadphonesIcon,
  'heart': HeartIcon,
  'heartbeat': HeartbeatIcon,
  'house': HouseIcon,
  'key': KeyIcon,
  'lamp': LampIcon,
  'laptop': LaptopIcon,
  'lightbulb': LightbulbIcon,
  'list-checks': ListChecksIcon,
  'map-pin': MapPinIcon,
  'microphone-stage': MicrophoneStageIcon,
  'microscope': MicroscopeIcon,
  'moon': MoonIcon,
  'mountains': MountainsIcon,
  'music-notes': MusicNotesIcon,
  'notebook': NotebookIcon,
  'paint-brush': PaintBrushIcon,
  'palette': PaletteIcon,
  'pen-nib': PenNibIcon,
  'pencil-line': PencilLineIcon,
  'person-simple-bike': PersonSimpleBikeIcon,
  'person-simple-run': PersonSimpleRunIcon,
  'phone': PhoneIcon,
  'piano-keys': PianoKeysIcon,
  'pill': PillIcon,
  'plant': PlantIcon,
  'presentation-chart': PresentationChartIcon,
  'puzzle-piece': PuzzlePieceIcon,
  'scissors': ScissorsIcon,
  'shopping-cart': ShoppingCartIcon,
  'shower': ShowerIcon,
  'smiley': SmileyIcon,
  'sneaker-move': SneakerMoveIcon,
  'star': StarIcon,
  'student': StudentIcon,
  'suitcase': SuitcaseIcon,
  'sun': SunIcon,
  'swimming-pool': SwimmingPoolIcon,
  't-shirt': TShirtIcon,
  'taxi': TaxiIcon,
  'television-simple': TelevisionSimpleIcon,
  'tent': TentIcon,
  'ticket': TicketIcon,
  'tooth': ToothIcon,
  'train': TrainIcon,
  'translate': TranslateIcon,
  'trash': TrashIcon,
  'umbrella': UmbrellaIcon,
  'users-three': UsersThreeIcon,
  'van': VanIcon,
  'video-camera': VideoCameraIcon,
  'washing-machine': WashingMachineIcon,
  'wine': WineIcon,
  'wrench': WrenchIcon,
}
